### ISSUE TITLE
Server does not work, stuck in fill loop after serving the first request.

### ISSUE THREAD

**Issue by mmagyar** [jFastCGI/jfastcgi#16]
I'm trying to interface my java app with apache2 with Fastcgi.
The problem is that after serving the first request, which reaches the client perfectly, all following requests are stuck, and it seems that it get's stuck in Input's fill  functions while loop.

I'm not sure if i'm doing something wrong, since i could not found any example code.

I'm going to post the code later, when i get home, but the gist of it is that i run fcgiinterfact.FcgiAccpet() in a while loop.

**Comment by jrialland** [comment]
There is a misunderstanding : This project do not provide any fastCGI implementation, but aims at providing a way for using a servlet container as a fastcgi "reverse proxy" for other fastcgi apps.

Therefore we cannot give you any help concerning the integration between your particular program and the fastCGI protocol, sorry :(

You may have a look at http://www.fastcgi.com/drupal/node/12 if you need help (we are not related with these people)

**Comment by mmagyar** [comment]
Sorry about that, i was just hoping this library could help with bidirectional communication, and since it kind of works, i was hoping it's supported.
