### ISSUE TITLE
Travis-ci.org integration

### ISSUE THREAD

**Issue by jrialland** [jFastCGI/jfastcgi#18]
I want to enable continuous integration using travis-ci.org
I've added a .travis.yml file, but builds have to be activated at  : https://travis-ci.org/profile/jFastCGI
Unfortunately Admin rights on the project are necessary for doing that ...

**Comment by domdorn** [comment]
i made you an owner... should have been like this anyway :)

**Comment by jrialland** [comment]
Thank you ! -- Now that travis integration is ok (https://travis-ci.org/jFastCGI/jfastcgi) I think I can close this issue
